apiVersion: v1
kind: Service
metadata:
  name: gui-assistant-apiserver
  namespace: management-platform
  labels:
    name: gui-assistant-apiserver
    namespace: management-platform
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30010
      protocol: TCP
  selector:
    name: gui-assistant-apiserver
    namespace: management-platform
