apiVersion: v1
kind: Service
metadata:
  name: opencsd-gui-assistant
  namespace: management-controller
  labels:
    name: opencsd-gui-assistant
    namespace: management-controller
spec:
  type: NodePort
  ports:
    - port: 40802
      targetPort: 40802
      nodePort: 30802
      protocol: TCP
  selector:
    name: opencsd-gui-assistant
    namespace: management-controller
